// <auto-generated />
using LanchoneteApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LanchoneteApi.Migrations
{
    [DbContext(typeof(LanchoneteContext))]
    partial class LanchoneteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LanchoneteApi.Models.Comanda", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcomanda");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_id"));

                    b.Property<bool>("StatusComanda")
                        .HasColumnType("boolean")
                        .HasColumnName("statuscomanda");

                    b.Property<int>("garcom_id")
                        .HasColumnType("integer")
                        .HasColumnName("garcom_id");

                    b.HasKey("_id");

                    b.HasIndex("garcom_id");

                    b.ToTable("comanda");
                });

            modelBuilder.Entity("LanchoneteApi.Models.Garcom", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idgarcom");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_id"));

                    b.Property<string>("NomeGarcom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nmgarcom");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("integer")
                        .HasColumnName("numeromesa");

                    b.HasKey("_id");

                    b.ToTable("garcom");
                });

            modelBuilder.Entity("LanchoneteApi.Models.ItemComanda", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iditemcomanda");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_id"));

                    b.Property<double>("VlVenda")
                        .HasColumnType("double precision")
                        .HasColumnName("vlvenda");

                    b.Property<int>("comanda_id")
                        .HasColumnType("integer")
                        .HasColumnName("comanda_id");

                    b.Property<int>("produto_id")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.HasKey("_id");

                    b.HasIndex("comanda_id");

                    b.HasIndex("produto_id");

                    b.ToTable("itemComanda");
                });

            modelBuilder.Entity("LanchoneteApi.Models.Produto", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idproduto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_id"));

                    b.Property<string>("Descricaoproduto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricaoproduto");

                    b.Property<string>("NmProduto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nmproduto");

                    b.Property<double>("VlProduto")
                        .HasColumnType("double precision")
                        .HasColumnName("vlproduto");

                    b.Property<int>("tipo_id")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_id");

                    b.HasKey("_id");

                    b.HasIndex("tipo_id");

                    b.ToTable("produto");
                });

            modelBuilder.Entity("LanchoneteApi.Models.Tipo", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idtipo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_id"));

                    b.Property<string>("NmTipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nmtipo");

                    b.HasKey("_id");

                    b.ToTable("tipo");
                });

            modelBuilder.Entity("LanchoneteApi.Models.Comanda", b =>
                {
                    b.HasOne("LanchoneteApi.Models.Garcom", "garcom")
                        .WithMany()
                        .HasForeignKey("garcom_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("garcom");
                });

            modelBuilder.Entity("LanchoneteApi.Models.ItemComanda", b =>
                {
                    b.HasOne("LanchoneteApi.Models.Comanda", "comanda")
                        .WithMany()
                        .HasForeignKey("comanda_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanchoneteApi.Models.Produto", "produto")
                        .WithMany()
                        .HasForeignKey("produto_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("comanda");

                    b.Navigation("produto");
                });

            modelBuilder.Entity("LanchoneteApi.Models.Produto", b =>
                {
                    b.HasOne("LanchoneteApi.Models.Tipo", "tipo")
                        .WithMany()
                        .HasForeignKey("tipo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipo");
                });
#pragma warning restore 612, 618
        }
    }
}
